# Generated by Django 5.1 on 2024-08-31 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dailyquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='options',
            field=models.ManyToManyField(related_name='attempts_options', to='api.option'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='questions',
            field=models.ManyToManyField(related_name='attempts_questions', to='api.question'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='subjects',
            field=models.ManyToManyField(related_name='chapters_subject', to='api.subject'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subjects',
            field=models.ManyToManyField(related_name='exams_subject', to='api.subject'),
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_question', to='api.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='chapter',
            field=models.ManyToManyField(related_name='questions_chapters', to='api.chapter'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ManyToManyField(related_name='questions_subjects', to='api.subject'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ManyToManyField(related_name='questions_topics', to='api.topic'),
        ),
        migrations.AlterField(
            model_name='question',
            name='years',
            field=models.ManyToManyField(related_name='questions_years', to='api.year'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solution_question', to='api.question'),
        ),
    ]
