# Generated by Django 5.1 on 2024-08-31 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_attempt_options_alter_attempt_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='options',
            field=models.ManyToManyField(to='api.option'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='questions',
            field=models.ManyToManyField(to='api.question'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='subjects',
            field=models.ManyToManyField(to='api.subject'),
        ),
        migrations.AlterField(
            model_name='dailyquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subjects',
            field=models.ManyToManyField(to='api.subject'),
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='chapter',
            field=models.ManyToManyField(to='api.chapter'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ManyToManyField(to='api.subject'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ManyToManyField(to='api.topic'),
        ),
        migrations.AlterField(
            model_name='question',
            name='years',
            field=models.ManyToManyField(to='api.year'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.question'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='topic',
            field=models.ManyToManyField(to='api.topic'),
        ),
    ]
