# Generated by Django 5.1 on 2024-10-28 18:38

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_userdetails_batch_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="batch_year",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1st Proff", "First Proff"),
                    ("2nd Proff", "Second Proff"),
                    ("3rd Proff - Part 1", "Third Proff Part 1"),
                    ("3rd Proff - Part 2", "Third Proff Part 2"),
                    ("Intern", "Intern"),
                    ("Post Intern", "Post Intern"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=20,
                null=True,
                validators=[api.models.validate_batch_year],
            ),
        ),
    ]
